local mod	= DBM:NewMod(416, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(14324)
mod:SetEncounterID(367)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:RegisterKill("yell", L.Defeat)
mod:DisableFriendlyDetection()

