local mod	= DBM:NewMod(407, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(11488)
mod:SetEncounterID(347)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:DisableFriendlyDetection()

