local mod	= DBM:NewMod(409, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(11496)
mod:SetEncounterID(349)
mod:SetModelID(14173)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:DisableFriendlyDetection()

