local mod	= DBM:NewMod(404, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(14327)
--mod:SetEncounterID(1443)
mod:SetModelID(14378)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:DisableFriendlyDetection()

