local mod	= DBM:NewMod(408, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(11487)
mod:SetEncounterID(348)
mod:SetModelID(14384)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:DisableFriendlyDetection()

