local mod	= DBM:NewMod(412, "DBM-Party-Vanilla", DBM:IsPostCata() and 3 or 6, 230)
local L		= mod:GetLocalizedStrings()
mod:SetRevision("@file-date-integer@")
mod:DisableHardcodedOptions()
mod:SetCreatureID(14322)
mod:SetEncounterID(363)
mod:SetZone(429)
mod:RegisterCombat("combat")
mod:DisableFriendlyDetection()

