name: DBM-Offline test diff
run-name: DBM-Offline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dbm-offline-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run DBM-Offline
        uses: DeadlyBossMods/DBM-Offline@main
        with:
          dbm-mod-ref-dungeons: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
          dbm-mod-base-ref-dungeons: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          test-dbm-dungeon-mods: true
          upload-repo-branch: diff-dungeons-${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}-${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          upload-token: ${{ secrets.TEST_RESULT_UPLOAD_TOKEN }}
          comment-token: ${{ secrets.GITHUB_TOKEN }}
